services:
  - type: web
    name: fruits-database-api
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 10000